# Generated by Django 6.0.5 on 2026-05-22 16:48

from django.db import migrations, models

import credentials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("password", models.CharField(blank=True, max_length=500, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "pem_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="credentials/pem_files/",
                        validators=[credentials.models.validate_pem_file],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Credential",
                "verbose_name_plural": "Credentials",
                "ordering": ["name"],
            },
        ),
    ]
