# Generated by Django 6.0.5 on 2026-05-22 17:35

from django.db import migrations

import credentials.fields


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="notes",
            field=credentials.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="password",
            field=credentials.fields.EncryptedTextField(
                blank=True, max_length=500, null=True
            ),
        ),
    ]
