# Generated by Django 6.0.5 on 2026-05-15 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="all_submitted",
        ),
        migrations.RemoveField(
            model_name="task",
            name="approval_status",
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
