# Generated by Django 6.0.5 on 2026-05-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name': 'Task Category', 'verbose_name_plural': 'Task Categories'},
        ),
    ]
