# Generated by Django 6.0.5 on 2026-05-21 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_taskcategory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_note", models.CharField(max_length=255)),
                (
                    "activity_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Activity",
                "verbose_name_plural": "Task Activities",
                "ordering": ["-activity_date", "-created_at"],
            },
        ),
    ]
