# Generated by Django 6.0.5 on 2026-05-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_all_submitted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskActivity',
        ),
    ]
