# Generated by Django 6.0.5 on 2026-05-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_taskactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="pending_with",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
