# Generated by Django 6.0.5 on 2026-05-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_pending_with"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["created_at"]},
        ),
    ]
