# Generated by Django 6.0.5 on 2026-06-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_task_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("terminated", "Terminated"),
                    ("waiting_for_approval", "Waiting For Approval"),
                    ("closed", "Closed"),
                ],
                default="not_started",
                max_length=27,
            ),
        ),
    ]
