# Generated by Django 6.0.5 on 2026-07-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_team_task_team_workarea_task_work_area_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workarea",
            name="description",
        ),
    ]
