# Generated by Django 6.0.5 on 2026-07-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_remove_workarea_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.RemoveField(
            model_name="task",
            name="team",
        ),
        migrations.RemoveConstraint(
            model_name="workarea",
            name="unique_work_area_per_team",
        ),
        migrations.RemoveField(
            model_name="task",
            name="work_area",
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.project",
            ),
        ),
        migrations.RemoveField(
            model_name="workarea",
            name="team",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.DeleteModel(
            name="WorkArea",
        ),
    ]
