# Generated by Django 6.0.5 on 2026-07-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_currency_paymentcard_paymenttiming_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptiontracker",
            name="platform",
            field=models.CharField(default="No Platform", max_length=150),
        ),
        migrations.DeleteModel(
            name="SubscriptionPlatform",
        ),
    ]
