# Generated by Django 6.0.5 on 2026-05-21 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registrar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="domainmanager",
            name="registrar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_management.registrar",
            ),
        ),
    ]
