# Generated by Django 6.0.5 on 2026-05-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_management", "0002_registrar_alter_domainmanager_registrar"),
    ]

    operations = [
        migrations.CreateModel(
            name="DNSZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("dns_records", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
