# Generated by Django 6.0.5 on 2026-05-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_management", "0003_dnszone"),
    ]

    operations = [
        migrations.AddField(
            model_name="webformmanager",
            name="last_tested_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
