# Generated by Django 6.0.5 on 2026-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportticket",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
