# Generated by Django 6.0.5 on 2026-05-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supportticket",
            old_name="completion_status",
            new_name="status",
        ),
    ]
