# Generated by Django 6.0.5 on 2026-05-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_completion_status_supportticket_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-last_updated_date', '-ticket_number'], 'verbose_name_plural': 'Support Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketrouting',
            options={'ordering': ['name'], 'verbose_name_plural': 'Ticket Routings'},
        ),
        migrations.AlterModelOptions(
            name='ticketstatus',
            options={'ordering': ['name'], 'verbose_name': 'Ticket Status', 'verbose_name_plural': 'Ticket Statuses'},
        ),
    ]
