# Generated by Django 6.0.5 on 2026-06-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_alter_supportticket_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="is_urgent",
            field=models.BooleanField(default=False),
        ),
    ]
